name: Run Commands on Self-Hosted Runner

on: 
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  run-commands:
    runs-on: [self-hosted,Linux,X64,metsl]
    
    steps:
    - name: Check out the code
      uses: actions/checkout@v3
    
    - name: Run commands
      run: |
        pwd
        ls -lrth
        sudo docker build -t sample-nginx . 
        sudo docker run -d -p 80:80 --name=sample-nginx sample-nginx
